# 📍 The Gateway takes over the Front Door
server.port=8080
spring.application.name=api-gateway

# 📡 Connect the Gateway to the Eureka Master Directory
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 🛑 Proactive Bug Fix: Force WebFlux, Kill Jersey
eureka.client.webclient.enabled=true
eureka.client.jersey.enabled=false

# 🗺️ THE ROUTING RULES
spring.cloud.gateway.routes[0].id=core-banking-route
spring.cloud.gateway.routes[0].uri=lb://CORE-BANKING-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**, /api/bank/**